// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrxCcm0zCFJItdyOgKqL4rQbwRG4IILQg',
    appId: '1:647658294177:web:0ef6b4e641e7ef4ec859e0',
    messagingSenderId: '647658294177',
    projectId: 'projectakhirmobilelanjut',
    authDomain: 'projectakhirmobilelanjut.firebaseapp.com',
    storageBucket: 'projectakhirmobilelanjut.appspot.com',
    measurementId: 'G-WXEFLYQ973',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIS6z-r8QVfQLDAJbH_D-yoiyMG34Fy1o',
    appId: '1:647658294177:android:f71ace7e8bf5a223c859e0',
    messagingSenderId: '647658294177',
    projectId: 'projectakhirmobilelanjut',
    storageBucket: 'projectakhirmobilelanjut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyz4WzuGRvIquVivJH6QsPObY1uzDzjCs',
    appId: '1:647658294177:ios:bcaa20fe19c846e3c859e0',
    messagingSenderId: '647658294177',
    projectId: 'projectakhirmobilelanjut',
    storageBucket: 'projectakhirmobilelanjut.appspot.com',
    iosBundleId: 'com.example.wargamart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyz4WzuGRvIquVivJH6QsPObY1uzDzjCs',
    appId: '1:647658294177:ios:6f4d1cadf5801ef7c859e0',
    messagingSenderId: '647658294177',
    projectId: 'projectakhirmobilelanjut',
    storageBucket: 'projectakhirmobilelanjut.appspot.com',
    iosBundleId: 'com.example.wargamart.RunnerTests',
  );
}
